### PR TITLE
fix: prevent overwriting 3rd party history data

### LINKED ISSUE #141: Do not owerwrite history state
Hello. Currently the browser plugin is overwriting the entire history state with the router state. Is it a better idea to have a namespaced entry in the global history state to not overwrite any third-party history state data? Thanks!

### PR DESCRIPTION
**Pull request by iotch**
Fixes #141, if I'm not mistaken...

### CODE REVIEW

File: modules/plugins/browser/index.js [hunk 1]
```diff
@@ -40,6 +40,7 @@ function browserPluginFactory(opts = {}, browser = safeBrowser) {
 
 
         function updateBrowserState(state, url, replace) {
+            state = { ...browser.getState(), ...state };
```
Comment (troch) [inline modules/plugins/browser/index.js]: `state` is shared with other consumers. Can you do `const finalState = ...`? Thanks!

**Comment by troch** [comment]
After having thought about this, I would put this behind a browser plugin option: it could be a breaking change for some users who don't expect that behaviour. I suggest naming the option `mergeState`.

**Comment by troch** [comment]
Thanks!
